# Generated by Django 5.2.7 on 2025-10-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('simple', 'Simple'), ('projet', 'Projet')], max_length=10)),
                ('categorie', models.CharField(choices=[('graphic_design', 'Graphic Design'), ('community', 'Community Management'), ('web_dev', 'Développement Web'), ('media_buying', 'Media Buying'), ('global', 'Projet Global')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='realisations/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='realisations/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='realisations/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='realisations/')),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('date_debut', models.CharField(blank=True, max_length=100, null=True)),
                ('date_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('afficher_accueil', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordre', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icone', models.CharField(max_length=10)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
