# Generated by Django 5.2.7 on 2025-10-08 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realisation',
            options={'ordering': ['ordre', '-date_creation'], 'verbose_name': 'Réalisation', 'verbose_name_plural': 'Réalisations'},
        ),
        migrations.RemoveField(
            model_name='realisation',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='realisation',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='realisation',
            name='image3',
        ),
        migrations.CreateModel(
            name='ImageRealisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='realisations/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.realisation')),
            ],
            options={
                'verbose_name': 'Image de Réalisation',
                'verbose_name_plural': 'Images de Réalisations',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
